[database]
url = "sqlite:///./trading.db"

[oanda]
api_key = "your_oanda_api_key_here"

[alphavantage]
api_key = "GARJ46JPDQ5H5PFW"
base_url = "https://www.alphavantage.co/query"

[api_keys]
alpha_vantage = "GARJ46JPDQ5H5PFW"

[data]
primary_source = "alphavantage"
fallback_source = "dukascopy"

[alphavantage.defaults]
interval = "60min"
output_size = "compact"

[ai]
enabled = true
model_name = "microsoft/DialoGPT-small"
model_type = "transformers"

[logging]
level = "INFO"
file = "trading_cli.log"

[backtest]
min_trades = 500
win_rate_threshold = 0.98
bootstrap_n = 10000

[slippage]
EURUSD = 2
GBPUSD = 2
XAUUSD = 5

[spread]
EURUSD = 0.1
GBPUSD = 0.2
XAUUSD = 0.3

[commission]
per_lot = 3.5
